### ISSUE TITLE
main branch does not build

### ISSUE THREAD

**Issue by ndastur** [geo-tp/ESP32-Bus-Pirate#50]
I've just checked out the repo and started a build. I get this error building the s3-devkit environment

```
In file included from /Users/xxx/.platformio/packages/framework-arduinoespressif32@src-b0a35cf7aa8c4c98d8eeed9e0597e1c2/cores/esp32/Arduino.h:202,
                 from src/Selectors/HorizontalSelector.h:8,
                 from src/Config/TerminalTypeConfigurator.h:3,
                 from src/Config/TerminalTypeConfigurator.cpp:1:
src/Config/TerminalTypeConfigurator.cpp: In member function 'TerminalTypeEnum TerminalTypeConfigurator::configure()':
/Users/xxxx/.platformio/packages/framework-arduinoespressif32@src-b0a35cf7aa8c4c98d8eeed9e0597e1c2/cores/esp32/HardwareSerial.h:413:16: error: 'HWCDCSerial' is not a member of 'TerminalTypeEnum'
  413 | #define Serial HWCDCSerial
      |                ^~~~~~~~~~~
src/Config/TerminalTypeConfigurator.cpp:9:60: note: in expansion of macro 'Serial'
    9 |         TerminalTypeEnumMapper::toString(TerminalTypeEnum::Serial),
```

I haven't changed anything and the build flags are:

```
build_flags =
  -D CONFIG_TINYUSB_ENABLED=1
  -D CONFIG_TINYUSB_CDC_ENABLED=1
  -D CONFIG_TINYUSB_HID_ENABLED=1
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CONFIG_CRC16_ENABLED=1 ; 1Wire EEPROM OneWireNg

  -DDEVICE_S3DEVKIT
```

I'm using:
PlatoformIO (Core 6.1.18·Home 3.4.4)
VSCode
OSX 15.3.1

**Comment by geo-tp** [comment]
I just built and I don’t have any particular problem. The most likely cause is that you’re using a different version of the Espressif arduino framework, which defines Serial in the code and conflicts with the TerminalTypeEnum Serial

**Comment by ndastur** [comment]
Thank you. Yes, probably. I did do a refactor to change to UsbSerial and get rid of the conflict but then loads of other build errors came up :(
Maybe version pinning is needed in platformIO. Do you know which espressif32 and ardinio version building works against?

**Comment by geo-tp** [comment]
In the `platformio.ini`, set the version like this to see if it fixes your problem

`platform = espressif32@6.8.1`

**Comment by ndastur** [comment]
Thank you. Yes, that builds on espressif32@6.8.1

I then went on to incrementally try versions to get the board: rymcu-esp32-s3-devkitc-1 building because that's not present in 6.8.1 ...  platform = espressif32@6.11.0 builds too.

So maybe at the top of platformio.ini ??
```
[env]
platform = espressif32@6.11.0
```

**Comment by ndastur** [comment]
I've submitted a PR for this.
There is also a new S3 board that is great for this project. About $2 on AE. I'm just testing the pinout defs on one and will submit a PR for the new board later

**Comment by geo-tp** [comment]
I don't think it's really necessary to specifically set the version, it should build by choosing the latest version without having to specify a version. On a clean Platformio, there are no build problems.

In your case, you may have had an Arduino Core already installed maybe, which caused the build errors.

Regarding the env for the board that you want to add, that would be a good addition

**Comment by ndastur** [comment]
Thanks. From what I can see, the problem is it doesn't build on the latest version. For instance in DioController.cpp there is a warning about ```ledcDetachPin(pin);``` in the latest version this now fails to build. Should be ```ledcDetach(pin);```
But on the latest there are quite a few other build errors :(

**Comment by geo-tp** [comment]
For me, when I specify no version, the latest version (6.12.0) is used, which is the latest official version of the framework.

I just tested it (with and without specifying version 6.12.0) and both work and build

**Comment by ndastur** [comment]
I'm sorry. You're right. Somehow a weird version was being pulled 54.3.1!! I had installed esptool from homebrew. Removing that seemed to help. Sorry for the report.
